name: turmalina_ui
description: Turmalina UI Kit package.

homepage: https://softyes.com.br
repository: https://github.com/turmalina-md/uikit

version: 0.1.0

environment:
  sdk: ^3.12.2
  flutter: ^3.44.4

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  very_good_analysis: ^10.3.0

flutter:
  uses-material-design: false
